version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_USER_PASSWORD}
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}"
    healthcheck:
      test: "mysql --user=root --password=root --execute \"SHOW DATABASES;\""

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    depends_on:
      db:
        condition: service_healthy
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://db:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE",
            "spring.datasource.username" : "$MYSQL_USER_NAME",
            "spring.datasource.password" : "$MYSQL_USER_PASSWORD",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'

  frontend:
    build:
      context: ./frontend
    ports:
      - "${REACT_LOCAL_PORT}:${REACT_DOCKER_PORT}"
    depends_on:
      - backend


